#!/bin/bash

echo "🔍 VÉRIFICATION DE LA CONFIGURATION RAILWAY BACKEND"
echo "===================================================="
echo ""

echo "📋 Variables requises pour le backend Railway:"
echo ""
echo "1. MYSQLHOST (fourni par Railway MySQL service)"
echo "2. MYSQLPORT (fourni par Railway MySQL service)"
echo "3. MYSQLDATABASE (fourni par Railway MySQL service)"
echo "4. MYSQLUSER (fourni par Railway MySQL service)"
echo "5. MYSQLPASSWORD (fourni par Railway MySQL service)"
echo "6. JWT_SECRET (à créer manuellement)"
echo "7. NODE_ENV=production"
echo "8. CORS_ORIGIN=https://gestion-chantier-kenia-production.up.railway.app"
echo ""

echo "⚠️  PORT ne doit PAS être défini manuellement (Railway le fournit automatiquement)"
echo ""

echo "===================================================="
echo "🎯 ACTIONS À FAIRE DANS RAILWAY:"
echo "===================================================="
echo ""

echo "1️⃣ Vérifier que MySQL est actif:"
echo "   - Dans Railway, liste des services"
echo "   - Service 'MySQL' doit avoir le badge 'Active' (vert)"
echo ""

echo "2️⃣ Configurer les variables dans Backend:"
echo "   a) Allez dans: Backend > Variables"
echo "   b) Cliquez sur 'New Variable' > 'Add Reference'"
echo "   c) Ajoutez ces variables avec références MySQL:"
echo ""
echo "      MYSQLHOST = \${{MySQL.MYSQLHOST}}"
echo "      MYSQLPORT = \${{MySQL.MYSQLPORT}}"
echo "      MYSQLDATABASE = \${{MySQL.MYSQLDATABASE}}"
echo "      MYSQLUSER = \${{MySQL.MYSQLUSER}}"
echo "      MYSQLPASSWORD = \${{MySQL.MYSQLPASSWORD}}"
echo ""
echo "   d) Ajoutez ces variables manuellement:"
echo ""
echo "      JWT_SECRET = un_secret_fort_et_unique_2025"
echo "      NODE_ENV = production"
echo "      CORS_ORIGIN = https://gestion-chantier-kenia-production.up.railway.app"
echo ""

echo "3️⃣ Vérifier que PORT n'est PAS défini manuellement:"
echo "   - Dans Variables, ne doit PAS y avoir de variable 'PORT'"
echo "   - Railway la fournit automatiquement"
echo ""

echo "4️⃣ Redéployer le backend:"
echo "   - Deployments > menu ⋮ > Redeploy"
echo ""

echo "===================================================="
echo "🔍 DIAGNOSTIC DES LOGS ACTUELS"
echo "===================================================="
echo ""

echo "Vos logs montrent:"
echo "  🚀 Serveur démarré sur le port 5000  ← PROBLÈME!"
echo "  Stopping Container"
echo ""
echo "Cela signifie:"
echo "  ❌ Le backend ne lit pas la variable PORT de Railway"
echo "  ❌ Il utilise le port par défaut 5000"
echo "  ❌ Railway attend le port 8080"
echo "  ❌ Railway arrête le container car il ne répond pas"
echo ""

echo "===================================================="
echo "✅ APRÈS CONFIGURATION CORRECTE"
echo "===================================================="
echo ""

echo "Les logs devraient montrer:"
echo ""
echo "  🚀 Démarrage de l'application Gestion Chantiers..."
echo "  ⏳ Attente de la base de données..."
echo "  📦 Mode production: vérification des migrations..."
echo "  ✅ Démarrage du serveur..."
echo "  🔒 CORS configuré pour: https://gestion-chantier-kenia-production.up.railway.app"
echo "  ✅ Connecté à la base de données MySQL"
echo "  🚀 Serveur démarré sur le port 8080  ← CORRECT!"
echo "  🌐 Environnement: production"
echo ""
echo "  (Le container ne s'arrête plus)"
echo ""

echo "===================================================="
echo "🧪 TEST FINAL"
echo "===================================================="
echo ""

echo "Une fois le backend redéployé avec les bonnes variables:"
echo ""
echo "  curl https://faithful-empathy-production.up.railway.app/api/health"
echo ""
echo "Devrait retourner:"
echo ""
echo '  {"status":"OK","timestamp":"...","database":"Connected"}'
echo ""

echo "===================================================="
echo ""
echo "📞 Si le problème persiste:"
echo "   - Copiez les nouveaux logs Railway"
echo "   - Vérifiez que MySQL est bien 'Active'"
echo "   - Vérifiez que toutes les variables \${{MySQL.*}} sont présentes"
echo ""
